name: dev-portal

on:
  push:
    branches:
      - '*'

jobs:
  replicate-file:
    runs-on: ubuntu-latest
    name: Replicate Readme Files

    steps:
      - name: Checkout Project A
        uses: actions/checkout@v2
        with:
          path: ./project

      - name: Checkout Project B
        uses: actions/checkout@master
        with:
          repository: Norigin/dev-portal
          token: ${{ secrets.NM_GH_TOKEN }}
          path: ./dev-portal

      - name: Move files
        run: |
          REPO_NAME=`basename "$PWD"`

          echo "Creating folder /docs/$REPO_NAME/"
          mkdir -p ./dev-portal/docs/$REPO_NAME/
          ls -la ./dev-portal/docs/$REPO_NAME/
          rm -rf ./dev-portal/docs/$REPO_NAME/*
          ls -la ./dev-portal/docs/$REPO_NAME/
          cp -R ./project/docs/ ./dev-portal/docs/$REPO_NAME/
          ls -la ./project/docs/
          echo "------"
          ls -la ./dev-portal/docs/$REPO_NAME/
          echo "Markdown files moved to /docs/$REPO_NAME/"
